config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", RedirectView.as_view(url="mainapp/")),
    path("mainapp/", include("mainapp.urls", namespace='mainapp')),

]

mainapp/urls.py
from django.urls import path

from mainapp import views
from mainapp.apps import MainappConfig

app_name = MainappConfig.name

urlpatterns = [
    path("", views.MainPageView.as_view(), name = 'main_page'),
    path("news/", views.NewsPageView.as_view(), name = 'news'),
    path("news/<int:page>/", views.NewsWithPaginatorView.as_view(), name = 'news_paginator'),
    path("courses_list/", views.CoursesPageView.as_view(),name = 'courses'),
    path("contacts/", views.ContactsPageView.as_view(), name = 'contacts'),
    path("doc_site/", views.DocSitePageView.as_view(), name = 'doc_site'),
    path("login/", views.LoginPageView.as_view(), name = 'login'),
]

mainapp/models.py
from random import choices, vonmisesvariate
from django.conf import settings
from django.db import models

NULLABLE = {'blank': True, 'null': True}

class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Дата изменения")

    deleted = models.BooleanField(default=False, verbose_name="Удален")

    class Meta:
        abstract = True
        ordering = ('-created_at',)

    def delete(self, *args, **kwargs):
        self.deleted = True
        self.save()

class NewsManager(models.Manager):

    def delete(self):
        pass

    def get_queryset(self):
        return super().get_queryset().filter(deleted=False)


class News(BaseModel):
    #objects = NewsManager()
    title = models.CharField(max_length=256, verbose_name="Заголовок")
    preamble = models.CharField(max_length=1024, verbose_name="Вступление")
    body = models.TextField(blank=True, null=True, verbose_name="Содержимое")
    body_as_markdown = models.BooleanField(default=False, verbose_name="Способ разметки")

    def __str__(self):
        return f"{self.pk} {self.title}"

    class Meta:
        verbose_name = 'новость'
        verbose_name_plural = 'новости'


class Course(BaseModel):
    name = models.CharField(max_length=256, verbose_name="Наименование курса")
    description = models.TextField(verbose_name="Описание", **NULLABLE)
    description_as_markdown = models.BooleanField(verbose_name="Способ разметки", default=False)
    cost = models.DecimalField(max_digits=8, decimal_places=2, verbose_name="Цена", default=0)
    cover = models.CharField(max_length=25, default="no_image.svg", verbose_name="Обложка")

    def __str__(self):
        return f"{self.pk} {self.name}"

    class Meta:
        verbose_name = 'курс'
        verbose_name_plural = 'курсы'

class Lesson(BaseModel):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    num = models.PositiveIntegerField(verbose_name="Номер урока")
    title = models.CharField(max_length=256, verbose_name="Наименование")
    description = models.TextField(verbose_name="Описание", **NULLABLE)
    description_as_markdown = models.BooleanField(verbose_name="Способ разметки", default=False)

    def __str__(self):
        return f"{self.course.name} | {self.num} | {self.title}"

    class Meta:
        verbose_name = 'урок'
        verbose_name_plural = 'уроки'
        ordering = ("course", "num",)

class CoursesTeacher(BaseModel):
    course = models.ManyToManyField(Course)
    name_first = models.CharField(max_length=128, verbose_name="Имя")
    name_second = models.CharField(max_length=128, verbose_name="Фамилия")
    day_birth = models.DateField(verbose_name="Дата рождения")

    def __str__(self):
        return "{0:0>3} {1} {2}".format(self.pk, self.name_second, self.name_first)



class CourseFeedback(BaseModel):
   
    RATINGS = (
        (5, '⭐⭐⭐⭐⭐'),
        (4, '⭐⭐⭐⭐'),
        (3, '⭐⭐⭐'),
        (2, '⭐⭐'),
        (1, '⭐'),
    )
    course = models.ForeignKey(Course, on_delete=models.CASCADE, verbose_name='Course')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='User')
    rating = models.SmallIntegerField(choices=RATINGS, default=5, verbose_name='rating')
    feedback = models.TextField(verbose_name='Feedback', default='No Feedback')

    class Meta:
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'

        def __str__(self):
            return f'Отзыв на {self.course} от {self.user}'

mainapp/forms.py
from django import forms

from mainapp.models import CourseFeedback

class CourseFeedbackForm(forms.ModelForm):

    def __init__(self, *args, course=None, user=None, **kwargs):
        ret = super().__init__(*args, **kwargs)
        if course and user:
            self.fields['course'].initial = course.pk
            self.fields['user'].initial = user.pk
        return ret

    class Meta:
        model = CourseFeedback
        fields = ('course', 'user', 'rating', 'feedback',)
        widgets = {
            'course' : forms.HiddenInput(),
            'user' : forms.HiddenInput(),
            
        }
    

mainapp/views.py
#from django.shortcuts import render
#from urllib3 import HTTPResponse
from django.http import HttpResponse
from tempfile import template

from django.views.generic import TemplateView
from datetime import datetime

# Create your views here.


class MainPageView(TemplateView):
    template_name = "mainapp/index.html"


class NewsPageView(TemplateView):
    template_name = "mainapp/news.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['news_title'] = "Громкий новостной заголовок"   
        context[
            "news_preview"
        ] = "Предварительное описание, которое заинтересует каждого"
        context["news_range"] = range(5)
        context["datetime_obj"] = datetime.now()
        return context
class CoursesPageView(TemplateView):
    template_name = "mainapp/courses_list.html"


class ContactsPageView(TemplateView):
    template_name = "mainapp/contacts.html"


class DocSitePageView(TemplateView):
    template_name = "mainapp/doc_site.html"


class LoginPageView(TemplateView):
    template_name = "mainapp/login.html"

class NewsWithPaginatorView(NewsPageView):
    def get_context_data(self, page, **kwargs):
        context = super().get_context_data(page=page, **kwargs)
        context["page_num"] = page
        return context

mainapp/templates/includes/feedback_card.html
<div class="card mb-3">
  <div class="card-body">
    <h5 class="card-title">{{ item.get_rating_display }}</h5>
    <h6 class="card-subtitle mb-2 text-muted">{{ item.user }}</h6>
    <p class="card-text">{{ item.feedback }}</p>
  </div>
</div>

mainapp/templates/includes/inc_main_menu.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
                <a class="navbar-brand" href="{% url 'mainapp:main_page' %}">
                <img src="{% static '/img/logo.png' %}" alt="">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item {% if request.resolver_match.view_name == 'mainapp:news' %} active {% endif %}">
                        <a class="nav-link" href="{% url 'mainapp:news' %}">Новости</a>
                    </li>
                    <li class="nav-item {% if request.resolver_match.view_name == 'mainapp:courses' %} active {% endif %}">
                        <a class="nav-link" href="{% url 'mainapp:courses' %}">Курсы</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="ddProfile" role="button" data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="false">
                            Профиль
                        </a>
                        <div class="dropdown-menu" aria-labelledby="ddProfile">
                            <a class="dropdown-item" href="#">Редактировать профиль</a>
                            <a class="dropdown-item" href="#">Мои курсы</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Модерация</a>
                            <a class="dropdown-item" href="#">Административный раздел</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Выход</a>
                        </div>
                    </li>
                    <li class="nav-item {% if request.resolver_match.view_name == 'mainapp:contacts' %} active {% endif %}">
                        <a class="nav-link" href="{%url 'mainapp:contacts' %}">Контакты</a>
                    </li>
                </ul>
                <span><a href="#">🇷🇺</a> <i class="fas fa-grip-lines-vertical"></i> <a href="#">🇬🇧</a></span>
            </div>
        </div>
    </nav>